[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
description = """
Library to support the reading of epub files.
"""
documentation = "https://docs.rs/epub/"
exclude = ["test.epub"]
keywords = [
    "epub",
    "ebook",
]
license = "GPL-3.0"
name = "epub"
repository = "https://github.com/danigm/epub-rs.git"
version = "1.2.3"
edition = "2018"

[dependencies]
percent-encoding = "2.1.0"
regex = "1.4.2"
xml-rs = "0.8.3"
zip = "0.5.8"
