name: Rust

on:
  push:
    paths:
    - "**/*.rs"
    - "**/*.yml"
    - "Cargo.toml"
    - "**/*.epub"
  pull_request:
    paths:
    - "**/*.rs"
    - "**/*.yml"
    - "Cargo.toml"
    - "**/*.epub"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable, 1.40.0]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
